version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - venv

  push_image:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install AWS CLI
          command: |
            pip install awscli

      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION \
            | docker login \
              --username AWS \
              --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - run:
          name: Build Docker Image
          command: |
            docker build -t docker-prac .

      - run:
          name: Tag Docker Image
          command: |
            docker tag docker-prac:latest \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/docker-prac:latest

      - run:
          name: Push Docker Image
          command: |
            docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/docker-prac:latest

workflows:
  version: 2

  build_and_push:
    jobs:
      - test

      - push_image:
          requires:
            - test
          filters:
            branches:
              only:
                - master
